ALTER TABLE users
  ADD COLUMN IF NOT EXISTS department VARCHAR(100),
  ADD COLUMN IF NOT EXISTS region VARCHAR(100),
  ADD COLUMN IF NOT EXISTS hub_location VARCHAR(100),
  ADD COLUMN IF NOT EXISTS certification_id VARCHAR(100),
  ADD COLUMN IF NOT EXISTS finance_unit VARCHAR(100);
