import type { Vehicle, Driver, Trip, Activity } from './types';

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    name: 'Semi Truck 1',
    licensePlate: 'FX-2024-001',
    capacity: 25000,
    odometer: 156240,
    status: 'on_trip',
    lastMaintenance: new Date('2024-01-15'),
    nextMaintenance: new Date('2024-04-15'),
    driver: 'd1',
  },
  {
    id: 'v2',
    name: 'Semi Truck 2',
    licensePlate: 'FX-2024-002',
    capacity: 25000,
    odometer: 89456,
    status: 'available',
    lastMaintenance: new Date('2024-02-01'),
    nextMaintenance: new Date('2024-05-01'),
  },
  {
    id: 'v3',
    name: 'Delivery Van 1',
    licensePlate: 'FX-2024-003',
    capacity: 5000,
    odometer: 34200,
    status: 'available',
    lastMaintenance: new Date('2024-02-10'),
    nextMaintenance: new Date('2024-05-10'),
  },
  {
    id: 'v4',
    name: 'Refrigerated Truck',
    licensePlate: 'FX-2024-004',
    capacity: 15000,
    odometer: 67890,
    status: 'in_shop',
    lastMaintenance: new Date('2023-12-20'),
    nextMaintenance: new Date('2024-03-20'),
  },
  {
    id: 'v5',
    name: 'Semi Truck 3',
    licensePlate: 'FX-2024-005',
    capacity: 25000,
    odometer: 234567,
    status: 'available',
    lastMaintenance: new Date('2024-01-30'),
    nextMaintenance: new Date('2024-04-30'),
    driver: 'd3',
  },
  {
    id: 'v6',
    name: 'Box Truck',
    licensePlate: 'FX-2024-006',
    capacity: 8000,
    odometer: 45600,
    status: 'on_trip',
    lastMaintenance: new Date('2024-02-05'),
    nextMaintenance: new Date('2024-05-05'),
    driver: 'd2',
  },
];

export const mockDrivers: Driver[] = [
  {
    id: 'd1',
    name: 'John Martinez',
    licenseType: 'Class A',
    licenseExpiry: new Date('2025-08-15'),
    status: 'on_duty',
    phone: '+1 (555) 123-4567',
    totalTrips: 487,
    rating: 4.8,
  },
  {
    id: 'd2',
    name: 'Sarah Chen',
    licenseType: 'Class A',
    licenseExpiry: new Date('2024-06-20'),
    status: 'on_duty',
    phone: '+1 (555) 234-5678',
    totalTrips: 312,
    rating: 4.9,
  },
  {
    id: 'd3',
    name: 'Michael Rodriguez',
    licenseType: 'Class A',
    licenseExpiry: new Date('2024-03-10'),
    status: 'on_duty',
    phone: '+1 (555) 345-6789',
    totalTrips: 654,
    rating: 4.6,
  },
  {
    id: 'd4',
    name: 'Jennifer Thompson',
    licenseType: 'Class B',
    licenseExpiry: new Date('2025-12-25'),
    status: 'off_duty',
    phone: '+1 (555) 456-7890',
    totalTrips: 201,
    rating: 4.7,
  },
  {
    id: 'd5',
    name: 'David Park',
    licenseType: 'Class A',
    licenseExpiry: new Date('2024-02-14'),
    status: 'on_duty',
    phone: '+1 (555) 567-8901',
    totalTrips: 543,
    rating: 4.5,
  },
  {
    id: 'd6',
    name: 'Amanda Wilson',
    licenseType: 'Class A',
    licenseExpiry: new Date('2025-11-30'),
    status: 'off_duty',
    phone: '+1 (555) 678-9012',
    totalTrips: 289,
    rating: 4.8,
  },
];

export const mockTrips: Trip[] = [
  {
    id: 'trip-001',
    vehicleId: 'v1',
    driverId: 'd1',
    cargoWeight: 18500,
    destination: 'Los Angeles, CA',
    pickupLocation: 'San Francisco, CA',
    status: 'dispatched',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'trip-002',
    vehicleId: 'v6',
    driverId: 'd2',
    cargoWeight: 4200,
    destination: 'Phoenix, AZ',
    pickupLocation: 'Las Vegas, NV',
    status: 'dispatched',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 'trip-003',
    vehicleId: 'v2',
    driverId: 'd4',
    cargoWeight: 12000,
    destination: 'Seattle, WA',
    pickupLocation: 'Portland, OR',
    status: 'draft',
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'trip-004',
    vehicleId: 'v3',
    driverId: 'd3',
    cargoWeight: 3100,
    destination: 'Denver, CO',
    pickupLocation: 'Salt Lake City, UT',
    status: 'completed',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 22 * 60 * 60 * 1000),
  },
  {
    id: 'trip-005',
    vehicleId: 'v5',
    driverId: 'd5',
    cargoWeight: 21000,
    destination: 'Chicago, IL',
    pickupLocation: 'Dallas, TX',
    status: 'completed',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
    completedAt: new Date(Date.now() - 46 * 60 * 60 * 1000),
  },
];

export const mockActivity: Activity[] = [
  {
    id: 'a1',
    type: 'trip_started',
    description: 'Trip trip-001 started by John Martinez',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    relatedId: 'trip-001',
  },
  {
    id: 'a2',
    type: 'trip_completed',
    description: 'Trip trip-005 completed successfully',
    timestamp: new Date(Date.now() - 46 * 60 * 60 * 1000),
    relatedId: 'trip-005',
  },
  {
    id: 'a3',
    type: 'driver_warning',
    description: 'Michael Rodriguez license expires in 18 days',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    relatedId: 'd3',
  },
  {
    id: 'a4',
    type: 'vehicle_maintenance',
    description: 'Semi Truck 1 scheduled maintenance completed',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    relatedId: 'v1',
  },
  {
    id: 'a5',
    type: 'driver_warning',
    description: 'David Park license expires in 24 days',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
    relatedId: 'd5',
  },
];
